In [1]:
import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 2.5.1


In [3]:
# 1D array from a list
arr1 = np.array([10, 52, 38, 74, 95])
print("1D array:", arr1)


1D array: [10 52 38 74 95]


In [4]:
# 2D array from a nested list (matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:\n", arr2)

2D array:
 [[1 2 3]
 [4 5 6]]


In [5]:
# 3D array
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D array:\n", arr3)

3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
# Array of zeros
zeros_arr = np.zeros((2, 3))
print("Zeros array:\n", zeros_arr)

Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
# Array of ones
ones_arr = np.ones((3, 2))
print("Ones array:\n", ones_arr)


Ones array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [8]:
# Array filled with a constant value
full_arr = np.full((2, 2), 7)
print("Full array:\n", full_arr)


Full array:
 [[7 7]
 [7 7]]


In [9]:
# arange -> similar to Python range() but returns an array
range_arr = np.arange(0, 10, 2)   # start, stop, step
print("arange array:", range_arr)



arange array: [0 2 4 6 8]


In [11]:
# Random arrays
rand_arr = np.random.rand(2, 3)      # uniform distribution [0, 1)
randint_arr = np.random.randint(1, 100, size=(2, 3))  # random integers
print("Random float array:\n", rand_arr)
print("Random integer array:\n", randint_arr)

Random float array:
 [[0.19564995 0.74336357 0.95566142]
 [0.11744736 0.50963182 0.71462448]]
Random integer array:
 [[21 60 99]
 [29 42  7]]


In [12]:
exercise1_a = np.zeros((4, 4))
exercise1_b = np.arange(10, 51, 5)
print(exercise1_a)
print(exercise1_b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[10 15 20 25 30 35 40 45 50]


In [13]:
sample = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", sample)
print("Shape:", sample.shape)     
print("Dimensions:", sample.ndim)  
print("Size:", sample.size)        
print("Data type:", sample.dtype)  

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2
Size: 6
Data type: int64


In [14]:
# Sorting arrays
unsorted = np.array([5, 2, 9, 1, 7])
sorted_arr = np.sort(unsorted)
print("Original:", unsorted)
print("Sorted:", sorted_arr)

Original: [5 2 9 1 7]
Sorted: [1 2 5 7 9]


In [15]:
ex2 = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", ex2.shape)
print("Size:", ex2.size)
print("Reshaped:\n", ex2.reshape(3, 2))

Shape: (2, 3)
Size: 6
Reshaped:
 [[1 2]
 [3 4]
 [5 6]]


In [16]:
x = np.array([10, 20, 30, 40])
y = np.array([1, 2, 3, 4])

print("Addition:", x + y)
print("Subtraction:", x - y)
print("Multiplication:", x * y)
print("Division:", x / y)
print("Power:", x ** 2)

Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]
Power: [ 100  400  900 1600]


In [17]:
data = np.array([4, 8, 15, 16, 23, 42])

print("Sum:", np.sum(data))
print("Mean:", np.mean(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))
print("Standard deviation:", np.std(data))
print("Variance:", np.var(data))

Sum: 108
Mean: 18.0
Minimum: 4
Maximum: 42
Standard deviation: 12.315302134607444
Variance: 151.66666666666666


In [18]:
# Universal functions work element-wise
nums = np.array([1, 4, 9, 16])

print("Square root:", np.sqrt(nums))
print("Exponential:", np.exp(nums))
print("Natural log:", np.log(nums))
print("Sine:", np.sin(nums))

Square root: [1. 2. 3. 4.]
Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
Natural log: [0.         1.38629436 2.19722458 2.77258872]
Sine: [ 0.84147098 -0.7568025   0.41211849 -0.28790332]


In [19]:
# Matrix operations
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

print("Element-wise multiplication:\n", m1 * m2)
print("Matrix multiplication (dot):\n", np.dot(m1, m2))
print("Matrix multiplication (matmul):\n", np.matmul(m1, m2))

Element-wise multiplication:
 [[ 5 12]
 [21 32]]
Matrix multiplication (dot):
 [[19 22]
 [43 50]]
Matrix multiplication (matmul):
 [[19 22]
 [43 50]]


In [20]:
arr = np.array([10, 20, 30, 40, 50, 60])

print("Full array:", arr)
print("First element:", arr[0])
print("Last element:", arr[-1])
print("Elements from index 1 to 3:", arr[1:4])
print("Every second element:", arr[::2])
print("Reversed array:", arr[::-1])

Full array: [10 20 30 40 50 60]
First element: 10
Last element: 60
Elements from index 1 to 3: [20 30 40]
Every second element: [10 30 50]
Reversed array: [60 50 40 30 20 10]
